// use require with a reference to bundle the file and use it in this file
// const example = require('./example')
const authEvents = require('./auth/events')
const unitEvents = require('./unit/events')
// use require without a reference to ensure a file is bundled
// require('./example')

$(() => {
  $('#sign-up-form').hide()
  $('#sign-up-button').on('click', () => { $('#sign-up-form').show() })
  $('#sign-up-form').on('submit', authEvents.onSignUp)
  $('#sign-in-form').hide()
  $('#login-button').on('click', () => { $('#sign-in-form').show() })
  $('#sign-in-form').on('submit', authEvents.onSignIn)
  $('#body-resource').hide()
  $('#change-pw-form').on('submit', authEvents.onChangePw)
  $('#sign-out-button').on('click', authEvents.onSignOut)
  $('#unit-input-form').on('submit', unitEvents.onUnitCreate)
  $('#get-units').on('click', unitEvents.onUnitsIndex)
  $('#unit-display').on('submit', '.update-unit', unitEvents.onUnitUpdate)
  $('#unit-display').on('click', '.delete-unit', unitEvents.onUnitDelete)
  $('#header').hide()
  $('#change-pw-form').hide()
  $('#change-pw-button').on('click', () => { $('#change-pw-form').show() })
})
